### ISSUE TITLE
第二部「はじめに」の次のページは「はじめに」

### ISSUE THREAD

**Issue by Takeno-hito** [traPtitech/naro-text#119]
一生始まらん

https://traptitech.github.io/naro-text/chapter2/

<img width="743" alt="image" src="https://github.com/traPtitech/naro-text/assets/18237819/c88c1da1-a95a-41f2-9b82-bcb1f6c5acfe">

**Comment by motoki317** [comment]
https://vitepress-lecture-template.trap.show/text/chapter-0/
https://git.trap.jp/kaitoyama/vitepress-lecture-template
では起こってないので、何かが違う？

**Comment by hijiki51** [comment]
https://vitepress.dev/reference/default-theme-prev-next-links

これでカスタマイズできる

**Comment by Takeno-hito** [comment]
#127 #138 にて fixed
