### ISSUE TITLE
サイドバーで今いるページのページ名のスタイルを変えたい

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/naro-text#15]
背景緑色にするとか

**Comment by hijiki51** [comment]
<img width="394" alt="image" src="https://github.com/traPtitech/naro-text/assets/19515624/642fa477-297a-40f3-9ae4-67b239468aaf">

されてない？

**Comment by hijiki51** [comment]
はじめに　みたいなトップだとされないのか

**Comment by mehm8128** [comment]
↑それも確かにそうなのですが、traQのテーマ入る前はGolangでHello Worldとかもされてなかったので、テーマ入れて直ったぽそうです
