### ISSUE TITLE
:::infoとかの使い方を統一してREADMEに書きたい

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/naro-text#16]
練習問題、注意事項、興味ある人だけ読んでほしい発展的な内容、など役割を決めたい

**Comment by hijiki51** [comment]
僕は
- tips: git/cliの操作法などの注釈
- warning: 注意事項（気を付けないと正常に実行できない）
- info: 発展的な内容、コラム


を想定してた。
練習問題はheadで区切って囲まない

**Comment by hijiki51** [comment]
答えはdetailsにしたほうがいいかも

**Comment by hijiki51** [comment]
dangerは基本使わない、使うとしたら破壊的な事象（サーバーが壊れる）などの時だけ使う

**Comment by mehm8128** [comment]
なるほど、よさそうです:blob_thumbs_up:
