### ISSUE TITLE
warningとかtipとかの中にコードブロック入れると背景色が同じで見づらい

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/naro-text#60]
こんな感じ
![image](https://github.com/traPtitech/naro-text/assets/83744975/610dab73-87bd-4853-af79-27592a2d93aa)

**Comment by hijiki51** [comment]
![image](https://github.com/traPtitech/naro-text/assets/19515624/597364ae-0ac1-4405-934c-dc710c1db4ab)

ちなみにダークモードは全然問題ない

**Comment by hijiki51** [comment]
![image](https://github.com/traPtitech/naro-text/assets/19515624/36d3868b-ac1d-4a50-85c8-8e6c1ca54740)
同じ場所

コードブロックは黒背景にそろえちゃってもいいかもね
